Models/DetalModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LAB_5.Models
{
    public class DetalModel
    {
        public int id { get; set; }

        [DisplayName("Название")]
        [Required]
        public string name { get; set; }

        [DisplayName("Цена")]
        public decimal cost { get; set; }

        public int Shop_Id { get; set; }

        [DisplayName("Производитель")]
        public string Shop_Name { get; set; }

        public List<BLL.ShopModel> shops { get; set; }
        public DetalModel() { }

        public DetalModel(List<BLL.ShopModel> shops)
        {
            this.shops = shops;
        }
        public DetalModel(BLL.DetalModel p, List<BLL.ShopModel> shops)
        {
            id = p.id;
            name = p.name;
            cost = decimal.Parse(p.cost);
            Shop_Id = p.Shop_Id;
            Shop_Name = shops.Where(i => i.id == p.Shop_Id).FirstOrDefault().name;
            this.shops = shops;
        }
    }
}

Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LAB_5.Models
{
    public class OrderModel
    {
        public string code { get; set; }
        public BLL.OrderModel Order { get; set; }
        public List<DetalModel> detals { get; set; }
    }
}

Models/ReportsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LAB_5.Models
{
    public class LinqReportModel
    {
        public List<BLL.Model.ReportModel.ReportData> ReportData { get; set; }
        public List<BLL.ShopModel> shops { get; set; }
        public int SelectShop_Id { get; set; }
    }
    public class ExecuteSP
    {
        public List<BLL.Model.ReportModel.SelectDetalName> DetalNames { get; set; }
        public List<BLL.DetalModel> detals;
        public int SelectDetal_Id { get; set; }
    }
}

Controllers/DetalController.cs
using LAB_5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LAB_5.Controllers
{
    public class DetalController : Controller
    {
        BLL.Interfaces.IDBCrud dBCrud;
        BLL.Interfaces.IOrderService service;

        public DetalController (BLL.Interfaces.IDBCrud dBCrud, BLL.Interfaces.IOrderService service)
        {
            this.dBCrud = dBCrud;
            this.service = service;
        }
        public ActionResult Index()
        {
            List<BLL.ShopModel> shopModels = dBCrud.GetShopModels();
            var model = new OrderModel() { detals = dBCrud.GetDetalModels().Select(i => new DetalModel(i, shopModels)).ToList(), Order = new BLL.OrderModel()  };
            return View("List", model);
        }
        public ActionResult Edit(int id)
        {
            List<BLL.ShopModel> shops = dBCrud.GetShopModels();
            DetalModel p = new DetalModel(dBCrud.GetDetal(id), shops);
            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(DetalModel model)
        {
            BLL.DetalModel det = new BLL.DetalModel();
            det.id = model.id;
            det.name = model.name;
            det.cost = model.cost.ToString();
            det.Shop_Id = model.Shop_Id;
            dBCrud.UpdateDetal(det);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new DetalModel(dBCrud.GetShopModels()));
        }

        [HttpPost]
        public ActionResult Create(DetalModel model)
        {
            BLL.DetalModel det = new BLL.DetalModel();
            det.name = model.name;
            det.cost = model.cost.ToString();
            det.Shop_Id = model.Shop_Id;

            dBCrud.CreateDetal(det);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            dBCrud.DeleteDetal(id);
            return RedirectToAction("Index");
        }

        public ActionResult CreateOrderDetal (OrderModel model)
        {
            List<BLL.ShopModel> shopModels = dBCrud.GetShopModels();
            model.detals = dBCrud.GetDetalModels().Select(i => new DetalModel(i, shopModels)).ToList();
            return View("BuyDetal", model);
        }
        [HttpPost]
        public ActionResult BuyDetal(OrderModel orderModel)
        {
            if (ModelState.IsValid)
            {
                if (service.CreateOrder(orderModel.Order, orderModel.code))
                    return RedirectToAction("Index");
            }
            List<BLL.ShopModel> shopModels = dBCrud.GetShopModels();
            orderModel.detals = dBCrud.GetDetalModels().Select(i => new DetalModel(i, shopModels)).ToList();
            return View("BuyDetal", orderModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LAB_5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/OrderController.cs
using BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LAB_5.Controllers
{
    public class OrderController : Controller
    {
        IDBCrud dBCrud;

        public OrderController(IDBCrud dBCrud)
        {
            this.dBCrud = dBCrud;
        }

        public ActionResult Index()
        {
            var items = dBCrud.GetOrderModels();
            return View(items);
        }
        public ActionResult Delete (int id)
        {
            dBCrud.DeleteOrder(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ReportsController.cs
using BLL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LAB_5.Controllers
{
    public class ReportsController : Controller
    {
        BLL.Interfaces.IDBCrud dBCrud;
        BLL.Interfaces.IReportService reportService;

        public ReportsController(IDBCrud dBCrud, IReportService reportService)
        {
            this.dBCrud = dBCrud;
            this.reportService = reportService;
        }

        public ActionResult LinqReport()
        {
            return View(new Models.LinqReportModel() { shops = dBCrud.GetShopModels() });
        }

        [HttpPost]
        public ActionResult LinqReport(Models.LinqReportModel model)
        {
            model.ReportData = reportService.reportDatas(model.SelectShop_Id);
            model.shops = dBCrud.GetShopModels();
            return View(model);
        }
        public ActionResult ExecuteSP()
        {
            return View(new Models.ExecuteSP() { detals = dBCrud.GetDetalModels() });
        }
        [HttpPost]
        public ActionResult ExecuteSP(Models.ExecuteSP model)
        {
            model.DetalNames = reportService.ExecuteSP(dBCrud.GetDetal(model.SelectDetal_Id).name);
            model.detals = dBCrud.GetDetalModels();
            return View(model);
        }
    }
}

Views/Detal/BuyDetal.cshtml
@model LAB_5.Models.OrderModel

@using (Html.BeginForm("BuyDetal", null))
{
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Order.id)

    <div class="form-group">
        @Html.LabelFor(model => model.Order.customer, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Order.customer)
            @Html.ValidationMessageFor(m => m.Order.customer)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Order.adress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Order.adress)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.code)
        </div>
    </div>
    <div class="form-group">
        @foreach (var item in Model.detals)
        {
            <div>
                <label>
                    <input type="checkbox" name="Order.DetalNumber" value="@item.id" checked="@Model.Order.DetalNumber.Contains(item.id)" /> @item.name
                </label>
            </div>
        }
        </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Заказать" class="btn btn-default" />
        </div>
    </div>
</div>
}
}

Views/Detal/Create.cshtml
@model LAB_5.Models.DetalModel

@{
    ViewBag.Title = "Добавить новую деталь";
    ViewBag.ButtonTitle = "Добавить";
}

@Html.Partial("_FormDetal", Model)

Views/Detal/Edit.cshtml
@model LAB_5.Models.DetalModel

@{
    ViewBag.Title = "Изменить деталь";
    ViewBag.ButtonTitle = "Изменить";
}


@Html.Partial("_FormDetal", Model)

<div>
    @Html.ActionLink("список деталей", "Index")
</div>

Views/Detal/List.cshtml
@model LAB_5.Models.OrderModel

@{
    ViewBag.Title = "Список деталей";
}
@using (Html.BeginForm("CreateOrderDetal", null, FormMethod.Get))
{
    <div margin="5">
        <p>
            @Html.ActionLink("Добавить", "Create")
        </p>
        <p>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Заказать" class="btn btn-default" />
                </div>
            </div>
        </p>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.detals[0].name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.detals[0].cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.detals[0].Shop_Name)
            </th>
        </tr>
        @foreach (var item in Model.detals)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shop_Name)
                </td>
                <td>
                    @Html.ActionLink("Изменить", "Edit", new { id = item.id })
                </td>
                <td>
                    @Html.ActionLink("Удалить", "Delete", new { id = item.id })
                </td>
                <td>
                    <div>
                        <label>
                            <input type="checkbox" name="Order.DetalNumber" value="@item.id" /> @item.name
                        </label>
                    </div>
                </td>
            </tr>

        }
    </table>
}

Views/Detal/_FormDetal.cshtml
@model LAB_5.Models.DetalModel
@using (Html.BeginForm()) 
{
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Shop_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shop_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Shop_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Shop_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Shop_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Shop_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ViewBag.ButtonTitle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}

<address>
    Работа выполнена:<br />
    <strong>Исаев Денис 3-42</strong><br />
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Магазин бытовой техники";
}

<div class="row">
    <br/><h1>Магазин бытовой техник</h1>
</div>
<div class="row">
    <p>
        веб-приложение разработонно студентом в учебных целях

    </p>
    <br /><p>Всего 6 вкладок:</p>
    <p>Главная - вы сейчас находитесь на ней</p>
    <p>Детали - отображает список деталей</p>
    <p>Заказы - показывает список зарегистрированных заказов</p>
    <p>Отчет - осуществляет фильтрация</p>
    <p>Отчет LINQ - осуществялет выборку методами LINQ</p>
</div>

Views/Order/Index.cshtml
@model IEnumerable<BLL.OrderModel>

@{
    ViewBag.Title = "Список заказов";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tabel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customer)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.adress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tabel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer)
        </td>
        <td>
            @Html.ActionLink("Удалить", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>

Views/Reports/ExecuteSP.cshtml
@model LAB_5.Models.ExecuteSP

@{
    ViewBag.Title = "Поиск детали";
}
<div class="row">
    <h1>Поиск детали</h1>
    @using (Html.BeginForm())
    {
        @Html.DropDownListFor(model => model.SelectDetal_Id, new SelectList(Model.detals, "Id", "Name"), new { @Style = "width:100%;" })
        <input type="submit" value="Найти" class="btn btn-default" />
    }
</div>

<div class="row">
    <table class="table">
        <tr>
            <th>
                Название Детали
            </th>
            <th>
                Стоимость
            </th>
        </tr>

        @if (Model.DetalNames != null)
        {
            foreach (var item in Model.DetalNames)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                </tr>
            }
        }
    </table>
</div>

Views/Reports/LinqReport.cshtml
@model LAB_5.Models.LinqReportModel

@{
    ViewBag.Title = "Детали по цеху";
}

<div class="row">
    <h1>Детали по цеху</h1>
    @using (Html.BeginForm())
    {
        @Html.DropDownListFor(model => model.SelectShop_Id, new SelectList(Model.shops, "Id", "Name"), new { @Style = "width:100%;" })
        <input type="submit" value="Найти" class="btn btn-default" />
    }
</div>

<div class="row">
    <table class="table">
        <tr>
            <th>
                Название детали
            </th>
            <th>
                Стоимость
            </th>
        </tr>

        @if (Model.ReportData != null)
        {
            foreach (var item in Model.ReportData)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DetalName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                </tr>
            }
        }
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Детали", "Index", "Detal")</li>
                    <li>@Html.ActionLink("Заказы", "Index", "Order")</li>
                    <li>@Html.ActionLink("Отчет", "ExecuteSP", "Reports")</li>
                    <li>@Html.ActionLink("Отчет LINQ", "LinqReport", "Reports")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer">
            <div class="container">
                @Html.ActionLink("Контакты", "Contact", "Home")
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>